name: 'Cross-Compile Support on Ubuntu'
description: 'Adds APT package repository for given arch and installs basic cross compile packages from it.'
inputs:
  arch:
    description: "A valid Ubuntu [arch] like arm64, armhf or i386"
    required: true
    default: "arm64"
runs:
  using: "composite"
  steps:
    - name: "Add Repository and install packages"
      shell: bash
      env:
        ARCH: ${{ inputs.arch }}
      run: |
        export CODENAME=$(lsb_release -c -s)
        export APTFILE=/etc/apt/sources.list.d/$ARCH-cross-compile-sources.list
        sudo dpkg --add-architecture $ARCH
        sudo bash -c "echo -e '\
          deb [arch=$ARCH] http://ports.ubuntu.com/ $CODENAME main restricted \n\
          deb [arch=$ARCH] http://ports.ubuntu.com/ $CODENAME-updates main restricted \n\
          deb [arch=$ARCH] http://ports.ubuntu.com/ $CODENAME universe \n\
          deb [arch=$ARCH] http://ports.ubuntu.com/ $CODENAME-updates universe \n\
          deb [arch=$ARCH] http://ports.ubuntu.com/ $CODENAME multiverse \n\
          deb [arch=$ARCH] http://ports.ubuntu.com/ $CODENAME-updates multiverse \n\
          deb [arch=$ARCH] http://ports.ubuntu.com/ $CODENAME-backports main restricted universe multiverse \n' > $APTFILE"
        sudo sed -i 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install \
          libstdc++-10-dev-$ARCH-cross \
          libstdc++6-$ARCH-cross \
          libc6-dev-$ARCH-cross \
          linux-libc-dev-$ARCH-cross
